# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFeatureCombinations < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.35"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.35/cargo-feature-combinations_0.0.35_darwin_arm64.tar.gz"
      sha256 "c7936b67b0ed4234b0ed4af646178bcbdf1bcc7ab6078a90333bd77fbfc32f0f"

      def install
        bin.install "cargo-feature-combinations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.35/cargo-feature-combinations_0.0.35_linux_arm64.tar.gz"
        sha256 "d15ac4fab55cfe9e946e056974ce8c051ceadd517e14d98a7be684eed01435e1"

        def install
          bin.install "cargo-feature-combinations"
        end
      end
    end
  end
end
