# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFeatureCombinations < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.33"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.33/cargo-feature-combinations_0.0.33_darwin_arm64.tar.gz"
      sha256 "ceb0cdffd2890a73486c741a3b0958173c250b49fd2be7379dd37d368b22718a"

      def install
        bin.install "cargo-fc"
        bin.install "cargo-feature-combinations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.33/cargo-feature-combinations_0.0.33_linux_arm64.tar.gz"
        sha256 "204c1add8c133d072ddb0f8685eef1bc7d5ff530e645ebc58a24ca98d63a0d9f"

        def install
          bin.install "cargo-fc"
          bin.install "cargo-feature-combinations"
        end
      end
    end
  end
end
