# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFeatureCombinations < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.30"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.30/cargo-feature-combinations_0.0.30_darwin_arm64.tar.gz"
      sha256 "f5f90dfb257d8898b69f39574e411cc3e447978230c2e7418ab67f0e6273aa8d"

      def install
        bin.install "cargo-fc"
        bin.install "cargo-feature-combinations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.30/cargo-feature-combinations_0.0.30_linux_arm64.tar.gz"
        sha256 "18a4e6e5f59f7612d562b4945ba956d36bc2b7569287a6c3871d832d69b5a26d"

        def install
          bin.install "cargo-fc"
          bin.install "cargo-feature-combinations"
        end
      end
    end
  end
end
