# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFc < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.35"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.35/cargo-fc_0.0.35_darwin_arm64.tar.gz"
      sha256 "7e875aa53762372c4537cd1ca9c611aaaaff8561b2241c04c0ca49d94521029a"

      def install
        bin.install "cargo-fc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.35/cargo-fc_0.0.35_linux_arm64.tar.gz"
        sha256 "17edb7f75dfa85f5a8fd7fc0590d72157371a62f599cb520bfb8dc3f1b0dfbb0"

        def install
          bin.install "cargo-fc"
        end
      end
    end
  end
end
