# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmux" do
  os macos: "darwin", linux: "linux"

  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "f87820ce2fd78dc26bb3a91d4bba6ec94f4daa02d73f95ebcb9cae0bbb9eba71"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3bec3538903dcf6414fe4837e0ba2a06e3a38c3a245a639306a15b45db5292c"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b261b936033472a8b77be520b9fb82d03dfa298c38658ca1d7cb772b677da207"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f860743ac6c8d405d86fe7c0c758b9a1e10e97db5604e27cbf1f0937d455d09"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentmux"
  desc "agentmux delegates a question to another vendor's coding agent and captures the whole transcript"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmux"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentmux"]
    end
  end

  # No zap stanza required

end
