# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmux" do
  os macos: "darwin", linux: "linux"

  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "e44d40f725d00fa15eb9aa6d0550bf20355681cda97bbeafec069813bfd30b5f"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "deebd50f2cd80d07fb5ede1e45f38a51ac30981925680905796052ab177e6929"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55a49fbdf1b8b4a6fe8a7339ec912c40356e28bd17fb9dfef336a5058509a61f"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98b2edb7b9dae2f53802fcaf57938449a489afb9f76211a1c5f03605aaf001e6"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentmux"
  desc "agentmux delegates a question to another vendor's coding agent and captures the whole transcript"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmux"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentmux"]
    end
  end

  # No zap stanza required

end
