# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmux" do
  os macos: "darwin", linux: "linux"

  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "fee0d4527171b6fddd90aa8fa16cd29ee68ab279decde86636098fcdda04e181"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7edf8f1b70c7f56e992d6843bd8d2e0c7f0ccd2f5790ea42028357f88b32d914"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c1cced0c56a44595c18b310d677e802e54e4749c3c8165a1763f3f331fc6c006"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc90cccf3b842665f25c2487d3f64b79c0cbfef3a9f5d809f2df7a4a77316ee4"
      url "https://github.com/romnn/agentmux/releases/download/v#{version}/agentmux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentmux"
  desc "agentmux delegates a question to another vendor's coding agent and captures the whole transcript"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmux"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentmux"]
    end
  end

  # No zap stanza required

end
