# This file was generated by GoReleaser. DO NOT EDIT.
cask "bumpversion" do
  name "bumpversion"
  desc "Update all version strings in your project and optionally commit and tag the changes"
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bumpversion"

  on_macos do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_darwin_amd64.tar.gz"
      sha256 "a29694b0801af2a4aa2b3ac58759e60c4865086c220bcb5cff0c4570343f8470"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_darwin_arm64.tar.gz"
      sha256 "54fe2c9c5e4e59842f048dcc595f6b18149932673167e2be8c03982ef11c2877"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_linux_amd64.tar.gz"
      sha256 "5fc91926adbfe5f2077b6ae52ca3166cda993eede349f62e2ff2963d8fb52983"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_linux_arm64.tar.gz"
      sha256 "94819d6d2970b10fa3e465e22dd314b6302c0d41d445e69275cdad253a4130d7"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bumpversion"]
    end
  end

  # No zap stanza required
end
