# This file was generated by GoReleaser. DO NOT EDIT.
cask "bumpversion" do
  os macos: "darwin", linux: "linux"

  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "067f5cd242914c7930e7b2109dfcc3a6a1542e3cd6d2a1aad8888a64360df9c7"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "056c6747b769a2d0c7e09bb82126127ba6f70ed74b10bd0423485771d8fead7f"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7201ff20bbbf448edf215c635d207e3439cb2e21e3a264421fd65c470a793e7e"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f26f836e654ccbfe028f43fc2b5d48901d79927f4f2833f4625291f035484c6d"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/bumpversion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bumpversion"
  desc "Update all version strings in your project and optionally commit and tag the changes"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bumpversion"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bumpversion"]
    end
  end

  # No zap stanza required

end
