# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-feature-combinations" do
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.41"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-feature-combinations"

  on_macos do
    on_intel do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.41/cargo-feature-combinations_0.0.41_darwin_amd64.tar.gz"
      sha256 "0d3357ac52ef9e36325be387109cacf532a4d11d47bb48010638bc223036c380"
    end
    on_arm do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.41/cargo-feature-combinations_0.0.41_darwin_arm64.tar.gz"
      sha256 "bbd24eda358e1670c9c1fe5b6ad9c67ef85dda6ddba76b26a3784708931d81a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.41/cargo-feature-combinations_0.0.41_linux_amd64.tar.gz"
      sha256 "ebea8d4e1a4985989489144354a08516263d0b311a17d510aae998b9cd0569a5"
    end
    on_arm do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.41/cargo-feature-combinations_0.0.41_linux_arm64.tar.gz"
      sha256 "393771b84aab071d36b96e6e3da8a65335264965f45a143729337444c95f649f"
    end
  end

  conflicts_with formula: [
      "cargo-feature-combinations",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-feature-combinations"]
    end
  end

  # No zap stanza required
end
