# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-publish-crates" do
  os macos: "darwin", linux: "linux"

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6763e7c5b7a0c6a475c5da63fc85c18c6474d4c2a697129a627cd73cea6c85da"
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a06fb6052b4ae8b67eef73d46e8b1b8a45934b29c0b808619baf31ca9a66ed7a"
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6c43fe0469d71f4c00e58043263101e79ee4d37c9f9413f9bb89a33f2044f67"
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56b6734e254f800c207e25b0d931bbb7ee87bcd709f771d827aca5ea01fce9ee"
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-publish-crates"
  desc "Publish rust crates with support for cargo workspaces"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-publish-crates"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-publish-crates"]
    end
  end

  # No zap stanza required

end
