# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-publish-crates" do
  name "cargo-publish-crates"
  desc "Publish rust crates with support for cargo workspaces"
  homepage ""
  version "0.0.28"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-publish-crates"

  on_macos do
    on_intel do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_amd64.tar.gz"
      sha256 "f8678239485988524cf7ed619b337fac55bc330d581e9444e952a525ba5f8c0e"
    end
    on_arm do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_arm64.tar.gz"
      sha256 "39f99addd78695f24f0862529bfeb1fc6ea3d539e5f1801166a7882cfd42657d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_amd64.tar.gz"
      sha256 "b0ce642fe293211eafa6e2a6246bd106341987cfd83bff710f011288cb31ef03"
    end
    on_arm do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_arm64.tar.gz"
      sha256 "64c75ac31b3b324503b26120ea662e68421d4bfc7a839ff895e08d50edd6a321"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-publish-crates"]
    end
  end

  # No zap stanza required
end
