# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-fc" do
  os macos: "darwin", linux: "linux"

  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "d6131c34cd40ba12496167a80e94328c2049461f90c6add8cf8bcbf8937bdb4b"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "477daf33d5ce3eb256b8b1b433218c1c84064c2b31fd17ecd61e7ad9f06b80a4"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6171d8159bd67a3385847cf36a70663c20c27224fc63fffca5280c8b0446c7e3"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b805276c8b72307b56dad0e7e71439d372542806f4fae5756489b0a2df01b1cc"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-fc"
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-fc"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-fc"]
    end
  end

  # No zap stanza required

end
