# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-dirty" do
  os macos: "darwin", linux: "linux"

  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f0f4f8932a88f41a9fb3998f3d20d1c954e258dc4a6cfb9fcd571cc048ab0c6b"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8b7a28cf41f3fea28cc53efde002819072e5fbc087ec5aad03380c1b73d833e"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0557b8832fb87044b6a9058efbd302893af7669f8fdb584782a126a9727c7357"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e14e9370ad3721d779cdbc440bc7ad80a6c6556fad61c7fab1efdb92251c0896"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-dirty"
  desc "Cargo subcommand that reports only what was recompiled."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-dirty"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-dirty"]
    end
  end

  # No zap stanza required

end
