# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-watchdoc" do
  name "cargo-watchdoc"
  desc "A CLI to generate and serve your `cargo doc` documentation with hot-reloading during development."
  homepage ""
  version "0.3.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-watchdoc"

  on_macos do
    on_intel do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_darwin_amd64.tar.gz"
      sha256 "0392298e04f7ab8a54c68423f248478dba6366a114804026819af866427cf75d"
    end
    on_arm do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_darwin_arm64.tar.gz"
      sha256 "b0b52f2b4349b24707837be8c261ef7757148b1eeae148b8046ab381d3203de9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_linux_amd64.tar.gz"
      sha256 "6b328ab29ff45597b08cdbf44d8fad431e745c28230e449cc63cdf4f3a050c4c"
    end
    on_arm do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_linux_arm64.tar.gz"
      sha256 "243e0121f494cdcdc0de73a3db44698017222c163751bb5770102aa362286868"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-watchdoc"]
    end
  end

  # No zap stanza required
end
