# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-publish-crates" do
  os macos: "darwin", linux: "linux"

  version "0.0.29"

  on_macos do
    on_intel do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_amd64.tar.gz"
      sha256 "59a03d3776a86b0ff1fec68c0ca15857d4e787a76b68d58242d428d4a4fcff53"
    end
    on_arm do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_darwin_arm64.tar.gz"
      sha256 "9494b1425ee5ede68d2a62f0a95a0926e0bc077c636d7d4815679da896ac4805"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_amd64.tar.gz"
      sha256 "3a8982226c1b51487d704ca95bc49c7b9fa8f25a47f3f72bc832ed46cc27be7f"
    end
    on_arm do
      url "https://github.com/romnn/publish-crates/releases/download/v#{version}/cargo-publish-crates_#{version}_linux_arm64.tar.gz"
      sha256 "4c0e7496f0a8b526ed18a1cacba66ae7c7f34621f2f927ce4fc73f7f7b1e2048"
    end
  end

  name "cargo-publish-crates"
  desc "Publish rust crates with support for cargo workspaces"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-publish-crates"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-publish-crates"]
    end
  end

  # No zap stanza required

end
