# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-fc" do
  os macos: "darwin", linux: "linux"

  version "0.0.53"

  on_macos do
    on_intel do
      sha256 "cceb66b3ac4bc4aefbd9284629c85578d7df21fa66910cb1e49f652ce1851400"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6142a7ccbf913cd18cf7be47231ccec59c81edd196065b21e12ea515e912c846"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88182a73e779cd2fbc42e66a86cdeb4165e6dbd8ed55a4ca8eb542b9dfca86a7"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d217bd1708de85ae668879e28bb49d148a1af50db96f25c52aa55df970ebdbc"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-fc"
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-fc"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-fc"]
    end
  end

  # No zap stanza required

end
