# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-dirty" do
  os macos: "darwin", linux: "linux"

  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "615ea859aeef5591f4c4ee910eb25881e5193bdbc8f5881d85ed22460567f5ac"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f281bef1a81834309bf386b32b9f53150010e742d0c8bec8bdfee1ea680d86da"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a73144711fb537dafd0abfeab619056fcbe5fdfd4a67451216e0954e940357ab"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffef1116ab5f1abed2d0c59ee2822920c64d3648a93a9c4e41a25969ddcbbba6"
      url "https://github.com/romnn/cargo-dirty/releases/download/v#{version}/cargo-dirty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-dirty"
  desc "Cargo subcommand that reports only what was recompiled."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-dirty"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-dirty"]
    end
  end

  # No zap stanza required

end
