# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-bumpversion" do
  name "cargo-bumpversion"
  desc "Plugin for `cargo` to update all version strings in your project and optionally commit and tag the changes"
  homepage ""
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-bumpversion"

  on_macos do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_amd64.tar.gz"
      sha256 "31e7942f791c1cfcacae44f7a2d092754616bbe73d71c809a47ea2830f661ba6"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_arm64.tar.gz"
      sha256 "0751dd8f2ec2554725a9255d5da4b4c6d476c7efcb619632b88448bc6a38bdeb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_amd64.tar.gz"
      sha256 "a3ba5e1ea6fffb30fd9ad18e837b90ec3efd5d116c030c0310fd1538fcd323e4"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_arm64.tar.gz"
      sha256 "f71b2fafe6dac11e7c4c7fd28d13d52bcfc565b5f767c2f2c1a6d043411f71bf"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-bumpversion"]
    end
  end

  # No zap stanza required
end
