# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-watchdoc" do
  os macos: "darwin", linux: "linux"

  version "0.3.10"

  on_macos do
    on_intel do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_darwin_amd64.tar.gz"
      sha256 "782f7dc232cc95a6f8b77eb7ae6f76b1abc4ad36b22754a9f75d4dcb85cf44e0"
    end
    on_arm do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_darwin_arm64.tar.gz"
      sha256 "8e1eb7d6304257b570e105462cb46a035c59f6945dabbaf1748c84e4e6a34a18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_linux_amd64.tar.gz"
      sha256 "624eeaf0b813b9add77b18058f3768b0e3f5b516d7c7fceddd37f229b01b4094"
    end
    on_arm do
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v#{version}/cargo-watchdoc_#{version}_linux_arm64.tar.gz"
      sha256 "0daf3e1d18f370b57e0146e8b84b85fa756821ac22c686b27e5353f1ac87d2cd"
    end
  end

  name "cargo-watchdoc"
  desc "A CLI to generate and serve your `cargo doc` documentation with hot-reloading during development."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-watchdoc"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-watchdoc"]
    end
  end

  # No zap stanza required

end
