# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-feature-combinations" do
  os macos: "darwin", linux: "linux"

  version "0.0.54"

  on_macos do
    on_intel do
      sha256 "33be8a8050a3b5fd1b2ff8e2f1734e53e6575f87733d49ab255599c29c1d0032"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6d1cfd566c3bf0d0ed97e0f7b875c6a8e0e140b2efd5cd6b923ad60146112ce"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7e1e58eec549c8146972fa021bbaae2e3ffdc7ce3479e8a54701676f95babdf"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b058ddfebd24c530825075de6132c3198aec8a74205bd8cccac8a4cb4ac978c9"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-feature-combinations"
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-feature-combinations"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-feature-combinations"]
    end
  end

  # No zap stanza required

end
