# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-fc" do
  os macos: "darwin", linux: "linux"

  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "3196236865bccedc9703e419c72408260e538028cbd1c2f1802bdfe8e031d980"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4469162078468909cab1de30839f3942cfe2ecabd97f021f7e4c140654cde112"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc90c539994bd13568b718ed214da4b031761cd36cf9c6d35b489fc665691cb6"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41b6599981832b2ca840ce220f362b8441879ee3096b675fda604cc2020e962e"
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-fc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-fc"
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-fc"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-fc"]
    end
  end

  # No zap stanza required

end
