# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-bumpversion" do
  name "cargo-bumpversion"
  desc "Plugin for `cargo` to update all version strings in your project and optionally commit and tag the changes"
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-bumpversion"

  on_macos do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_amd64.tar.gz"
      sha256 "51c237023306a8168e62aeca692d0224958578a72ae8d29069b2be7dc9af0773"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_arm64.tar.gz"
      sha256 "f560d1ffad5ebcb39366d68159be94dde98e1094fa365a1837031044b789ffeb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_amd64.tar.gz"
      sha256 "054ed9230aa1f2d2384a5e2f5b9adf7eac308d0c9a5edacbf196f36b25eef472"
    end
    on_arm do
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_arm64.tar.gz"
      sha256 "0bd45444beab0dacd7054786b5742669ee52b424963d1121f3e8559507ee98a6"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-bumpversion"]
    end
  end

  # No zap stanza required
end
