# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-feature-combinations" do
  version "0.0.48"

  on_macos do
    on_intel do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_darwin_amd64.tar.gz"
      sha256 "e0e30b5a71bdaacb06c9dcdaf4c77bf6427519695b912347726d55768ee658c1"
    end
    on_arm do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_darwin_arm64.tar.gz"
      sha256 "8e802bd424abf232fa87c5ddedae945b535ed39543e49e7a2fb979f1502d9efd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_linux_amd64.tar.gz"
      sha256 "7b08609c1eedf83b205cfa4d977cbfab25a85ccf848b53c66d0668674883d1c0"
    end
    on_arm do
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v#{version}/cargo-feature-combinations_#{version}_linux_arm64.tar.gz"
      sha256 "06e073954800b4297f0e4217ed6ace68fcfcabc525d25fe032c671c3a975f3ea"
    end
  end

  name "cargo-feature-combinations"
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-feature-combinations"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-feature-combinations"]
    end
  end

  # No zap stanza required

end
