# This file was generated by GoReleaser. DO NOT EDIT.
cask "cargo-bumpversion" do
  os macos: "darwin", linux: "linux"

  version "0.0.11"

  on_macos do
    on_intel do
      sha256 "9e49fdf9af81fd2a8b7e7811c6bfbd2784a7540012d5aada5bb8dcb850507598"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c1c35dec35a50f07286e19245b3336c0f335d4c65c13c3ad5d7eefc4a7ab4db"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b80a0ed8f920156e5fde206c92bc39aa69e191e33bcac916fa69ca3bab151370"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74d33c7020ffc5b4b03bfb81f18ccf20fb253142aedaa0775108320380631a13"
      url "https://github.com/romnn/bumpversion/releases/download/v#{version}/cargo-bumpversion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cargo-bumpversion"
  desc "Plugin for `cargo` to update all version strings in your project and optionally commit and tag the changes"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cargo-bumpversion"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cargo-bumpversion"]
    end
  end

  # No zap stanza required

end
