# This file was generated by GoReleaser. DO NOT EDIT.
cask "confirm" do
  name "confirm"
  desc "A dead simple CLI app that asks the user for a yes/no confirmation"
  homepage ""
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confirm"

  on_macos do
    on_intel do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_darwin_amd64.tar.gz"
      sha256 "464baa639204c220b01cd25b310522c27f7591b7a73b5189cf2d14de34d3efc1"
    end
    on_arm do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_darwin_arm64.tar.gz"
      sha256 "3c5e373d6c42edbd9b3dca41250cc981061a2beab050c6ced2cc11a57c9c59fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_linux_amd64.tar.gz"
      sha256 "d44d49354fea63acefe876dfb847a3554db7c64a29f9b132c33c00ffd4a47435"
    end
    on_arm do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_linux_arm64.tar.gz"
      sha256 "0dcac55a13e37fc69a022a51828b5f2ed81973728eb7073e8c8b22c6b8e2b71c"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confirm"]
    end
  end

  # No zap stanza required
end
