# This file was generated by GoReleaser. DO NOT EDIT.
cask "confirm" do
  name "confirm"
  desc "A dead simple CLI app that asks the user for a yes/no confirmation"
  homepage ""
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "confirm"

  on_macos do
    on_intel do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_darwin_amd64.tar.gz"
      sha256 "07d9a0fb8dda1ea72decf2001ab1610f7c5f323a326e86d3e641b511f4285296"
    end
    on_arm do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_darwin_arm64.tar.gz"
      sha256 "f174b3250693a9ae3e006715accaebbf319d9ee671157af9e06de98dddcf95ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_linux_amd64.tar.gz"
      sha256 "152a3af80559398223446a79850d9093c64ed921decf7e41f4723d745f2343f7"
    end
    on_arm do
      url "https://github.com/romnn/confirm/releases/download/v#{version}/confirm_#{version}_linux_arm64.tar.gz"
      sha256 "b5c16bc3a864bc6bde2e2cc7b5f10fd4d55440602d5a7526dddb504d6608ba8c"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/confirm"]
    end
  end

  # No zap stanza required
end
