# This file was generated by GoReleaser. DO NOT EDIT.
cask "cooldown" do
  os macos: "darwin", linux: "linux"

  version "0.0.13"

  on_macos do
    on_intel do
      sha256 "47d1316d7d45d96eb99f05418542887bb9648d03df575bae1b239f081073bb91"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a46ba7ac43a3ff1261b001c4ab3285c3c2d0cf84b7b47e42bb0003a08117add"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "651ce4f646e73989b9dc507303b2ba52d3bf0165625e1d4b18980a7be736e6c2"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1338d8538c974af154ec57a5ad4a6fd04d5c8a35add43c1c94be83db61ced23"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cooldown"
  desc "A unified, language-agnostic dependency-cooldown CLI: refuse to adopt any version younger than a minimum release age, across tools, from one policy core."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cooldown"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cooldown"]
    end
  end

  # No zap stanza required

end
