# This file was generated by GoReleaser. DO NOT EDIT.
cask "cooldown" do
  os macos: "darwin", linux: "linux"

  version "0.0.25"

  on_macos do
    on_intel do
      sha256 "09c54a1e3582ab43d93377cd7c4d327ba7306d0e8bf6aa3c8786a38cd14bd0b2"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b2dafd66a96c643f0e0cbb91c86977eaed7a85d6482e225cb25f80600dd6f22"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8704f5b7062c68920bb96fe08dcd769e04a77e02a0096bbf272692d65fcd1c0"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "707a8ac64f4977890f5aafa3066f296ade8fffb18240f149cb5fcc93e3eaf116"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cooldown"
  desc "A unified, language-agnostic dependency-cooldown CLI: refuse to adopt any version younger than a minimum release age, across tools, from one policy core."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cooldown"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cooldown"]
    end
  end

  # No zap stanza required

end
