# This file was generated by GoReleaser. DO NOT EDIT.
cask "cooldown" do
  os macos: "darwin", linux: "linux"

  version "0.0.22"

  on_macos do
    on_intel do
      sha256 "a8ae63abc35740027ff029f4ed625a647c0ed0812f2acb7282d5f43c7cadb8f9"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "706f78c464051f769c3178a817cf0c53f2d6104f84d75df1c89dc6aaf6bfef84"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c5e9d530eb955001560def0e9bca18be1de8a1fcfa4015b3b1dcb9ecc011e902"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59adfa43623e6a1b261e2dec92ea0cfb3985aac03be22f79c8092bc85d391680"
      url "https://github.com/romnn/cooldown/releases/download/v#{version}/cooldown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cooldown"
  desc "A unified, language-agnostic dependency-cooldown CLI: refuse to adopt any version younger than a minimum release age, across tools, from one policy core."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cooldown"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cooldown"]
    end
  end

  # No zap stanza required

end
