# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-schema" do
  os macos: "darwin", linux: "linux"

  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "c1d64ac4c48d27160bd2e40dcd4ab2119429057b4da9ff5926024829391d4bd7"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5a2a60868115ace819b07cb4441fec75da1250c6cb849ef5eefda6a1ce7bfcb"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "568d65f8289d90b957071ce2bd8e5c0ff68f73021fa8229b9f08597494b4d185"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a43edd9a7e01c9938f18a3ec88cddbed1196baa4197cde47150a24eb095aaa7"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-schema"
  desc "helm-schema generates a JSON schema for a helm chart's values.yaml by analyzing the chart's templates"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-schema"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/helm-schema"]
    end
  end

  # No zap stanza required

end
