# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-schema" do
  os macos: "darwin", linux: "linux"

  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "377da32ae100e42c474bd3c6688d8214f51919eaf91865ab70f89550b6fdeab1"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da21c2346e7fab2f83b581e04ed5506f896ee8a0974c9c195f16439f2610c3a4"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07340d6bc31b3e0ceb05250713b4815f30083a5c52600b12cf800a974556be11"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af75705dee5fa84bff9a1eac0db61baafac7b15249e68d063427927685278b53"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-schema"
  desc "helm-schema generates a JSON schema for a helm chart's values.yaml by analyzing the chart's templates"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-schema"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/helm-schema"]
    end
  end

  # No zap stanza required

end
