# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-schema" do
  os macos: "darwin", linux: "linux"

  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "c2d23c1b6df4ef18bf33c18efcbae5e848d6d5945922905166f818fcdbb70182"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54df7f78afc7efc4dee20b0bbaa585c4a1d70ded6cfec077df1cb557c845b2a6"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a322093ee1df70b1ad5044442ab798ed3f8d2451ad344c220ca35ac2836707c"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c4ede6808bd73512c70596bb07fad289f5ee114f558a1c3a7a57dcfd08b0b55"
      url "https://github.com/romnn/helm-schema/releases/download/v#{version}/helm-schema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-schema"
  desc "helm-schema generates a JSON schema for a helm chart's values.yaml by analyzing the chart's templates"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-schema"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/helm-schema"]
    end
  end

  # No zap stanza required

end
