# This file was generated by GoReleaser. DO NOT EDIT.
cask "micromux" do
  name "micromux"
  desc "Micromux is a local process supervisor with a terminal UI"
  homepage ""
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "micromux"

  on_macos do
    on_intel do
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_amd64.tar.gz"
      sha256 "8b4cb68cbb864f169d529a827addb5c46622d85425746570b5893b6196cd65a1"
    end
    on_arm do
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_arm64.tar.gz"
      sha256 "7256fb76595338658d9aa2cfdf9d464b6ac2c7732b820429096fc4615d3026f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_amd64.tar.gz"
      sha256 "2247502022c3acc6238e0c6b9aa5deb766b8f0257bafd91efeb0d68daecdf473"
    end
    on_arm do
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_arm64.tar.gz"
      sha256 "58dcca3ca811a27720ec371fa438d3cf1d64e4a7a5761280942694bc0aa47176"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/micromux"]
    end
  end

  # No zap stanza required
end
