# This file was generated by GoReleaser. DO NOT EDIT.
cask "micromux" do
  os macos: "darwin", linux: "linux"

  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "e306ca9a4013e10269b1afc31026d1799e0b55bd9d8ce66d53a3699fbf4fa664"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7feedc786da4f22369cfe43d9932cea91a4bdc3e44eddd8c7af76a29e155c814"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66ea8fb606c8dbe94ac83c2c487541827ebf9b313d8974e1df5eb4417a8cbb52"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c269f85cd6ab0a3197a42d678a6714f942d53a0fb14b12d3bc598ac87b2aa15b"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "micromux"
  desc "Micromux is a local process supervisor with a terminal UI"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "micromux"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/micromux"]
    end
  end

  # No zap stanza required

end
