# This file was generated by GoReleaser. DO NOT EDIT.
cask "micromux" do
  os macos: "darwin", linux: "linux"

  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2b0df585e2b813a4ff9fbe5ca7624b0299f6b6d2473004d2aefc17c9856ed061"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f72db38c414a25c39f34b9846216c41cd51a29b7914873d9e42d765bc3980642"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e4ef4975a5ce110b91b80469898ad78b3962a76b62c0aff1dc63c6269402304"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f49f94588123c760643a40d79b16a51e4e31d9fedba2b021e824a50e632a6a99"
      url "https://github.com/romnn/micromux/releases/download/v#{version}/micromux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "micromux"
  desc "Micromux is a local process supervisor with a terminal UI"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "micromux"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/micromux"]
    end
  end

  # No zap stanza required

end
