# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bumpversion < Formula
  desc "Update all version strings in your project and optionally commit and tag the changes"
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/bumpversion_0.0.5_darwin_amd64.tar.gz"
      sha256 "faeaa97be842246e769f2982bed8c19e29cc7485bb1686c71586071d452dca38"

      def install
        bin.install "bumpversion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/bumpversion_0.0.5_darwin_arm64.tar.gz"
      sha256 "362c911b6feb10765f36646a1c72f77742fb159b44644342481798148393c123"

      def install
        bin.install "bumpversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/bumpversion_0.0.5_linux_amd64.tar.gz"
        sha256 "03338c8cd265a00a022aa8ded177f0f52ea6210791945b15c59163ff339628dc"

        def install
          bin.install "bumpversion"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/bumpversion_0.0.5_linux_arm64.tar.gz"
        sha256 "87792b10406a42f2e6ae9bce0cc2a2cc191da735edbcce5b1855c68621b21881"

        def install
          bin.install "bumpversion"
        end
      end
    end
  end
end
