# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoWatchdoc < Formula
  desc "A CLI to generate and serve your `cargo doc` documentation with hot-reloading during development."
  homepage ""
  version "0.3.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-watchdoc/releases/download/v0.3.4/cargo-watchdoc_0.3.4_darwin_arm64.tar.gz"
      sha256 "c655eb2f861a4ca259a8537ff1c12e17cef0e2456bd591c42082c5f899bb90d1"

      def install
        bin.install "cargo-watchdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-watchdoc/releases/download/v0.3.4/cargo-watchdoc_0.3.4_linux_arm64.tar.gz"
        sha256 "f0e8d798c11e63495ae5f01b1355e2d28fdce30e3cccce3e7f8a5b793bb41850"

        def install
          bin.install "cargo-watchdoc"
        end
      end
    end
  end
end
