# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoPublishCrates < Formula
  desc "Publish rust crates with support for cargo workspaces"
  homepage ""
  version "0.0.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/publish-crates/releases/download/v0.0.24/cargo-publish-crates_0.0.24_darwin_amd64.tar.gz"
      sha256 "409a4671f38ee6cfa2119dd01e83e624e28ebf840597278eca0b9f8cd41422cc"

      def install
        bin.install "cargo-publish-crates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/publish-crates/releases/download/v0.0.24/cargo-publish-crates_0.0.24_darwin_arm64.tar.gz"
      sha256 "330d85cd79175793053391b56657838f97d133a4cfcd070d7d0aecd9632a74f9"

      def install
        bin.install "cargo-publish-crates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/publish-crates/releases/download/v0.0.24/cargo-publish-crates_0.0.24_linux_amd64.tar.gz"
        sha256 "c75ea1ca88bcf8794abcc6bca690438ca98d4f7a8c1e1471786f93b7ae27d884"

        def install
          bin.install "cargo-publish-crates"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/publish-crates/releases/download/v0.0.24/cargo-publish-crates_0.0.24_linux_arm64.tar.gz"
        sha256 "d6aad0bf9d63ec3b74ea038dcef13e6374123ce25d2f4ab7d02fd8fef449b23d"

        def install
          bin.install "cargo-publish-crates"
        end
      end
    end
  end
end
