# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoBumpversion < Formula
  desc "Plugin for `cargo` to update all version strings in your project and optionally commit and tag the changes"
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/cargo-bumpversion_0.0.5_darwin_amd64.tar.gz"
      sha256 "5a8e29a03ffa405e5caa69e9323a4a57b291bcad02a31ea310f79eac70ae74c0"

      def install
        bin.install "cargo-bumpversion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/cargo-bumpversion_0.0.5_darwin_arm64.tar.gz"
      sha256 "64b54b16bf0a74f7324880ee36455386abb9b7f61c4d9827628c71c7adc0a187"

      def install
        bin.install "cargo-bumpversion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/cargo-bumpversion_0.0.5_linux_amd64.tar.gz"
        sha256 "651f53debe3101738fb73f18d7fe09ab4d0de62d692d0ff36e1c5c917c50bdf7"

        def install
          bin.install "cargo-bumpversion"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/bumpversion/releases/download/v0.0.5/cargo-bumpversion_0.0.5_linux_arm64.tar.gz"
        sha256 "68263ad04bd11688aab75eea35cca6b2763e5af7eb506a7238d3abed7276a8cd"

        def install
          bin.install "cargo-bumpversion"
        end
      end
    end
  end
end
