# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFc < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-fc_0.0.38_darwin_amd64.tar.gz"
      sha256 "2ba5720448bb615643be502fdd2c3dce9fe64b77951a8427d09fa6049494025e"

      def install
        bin.install "cargo-fc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-fc_0.0.38_darwin_arm64.tar.gz"
      sha256 "872fcb7069c5c9b6b455c84e5aaea81ee89f443b0413c0ee2d23ddf4fea8da12"

      def install
        bin.install "cargo-fc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-fc_0.0.38_linux_amd64.tar.gz"
        sha256 "42e484ae98c3a7df14fff820979fb612a729a99408cc00c3cbf3bf83f9e3d23d"

        def install
          bin.install "cargo-fc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-fc_0.0.38_linux_arm64.tar.gz"
        sha256 "3c58309bf25096cd0735c7f2320cabd4556a1b9d6bf34dc827fb0cca9b9f0564"

        def install
          bin.install "cargo-fc"
        end
      end
    end
  end
end
