# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFeatureCombinations < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-feature-combinations_0.0.38_darwin_amd64.tar.gz"
      sha256 "a9380c2a2eda9b0bfa5059ac7734a6434b25a2162b3deb14df8bf8d4446c33d8"

      def install
        bin.install "cargo-feature-combinations"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-feature-combinations_0.0.38_darwin_arm64.tar.gz"
      sha256 "2bdf3e98b4a6ac6c2e0eb2362cbb2154aca6c54c2203d91a3aed00f7ab3447c5"

      def install
        bin.install "cargo-feature-combinations"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-feature-combinations_0.0.38_linux_amd64.tar.gz"
        sha256 "62808b95e73dc1d5dc1bc40e256a28a2ff77ab0413b705b79ddc702573f17efe"

        def install
          bin.install "cargo-feature-combinations"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.38/cargo-feature-combinations_0.0.38_linux_arm64.tar.gz"
        sha256 "ccf94998a54988fd5784b5193fda966ba4b2db9878300c321a7f545c04b497ae"

        def install
          bin.install "cargo-feature-combinations"
        end
      end
    end
  end
end
