# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CargoFc < Formula
  desc "Plugin for `cargo` to run commands against selected combinations of features."
  homepage ""
  version "0.0.40"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.40/cargo-fc_0.0.40_darwin_amd64.tar.gz"
      sha256 "8b7d3ee66b33dc11eebb1891003b6337775145350900d67fc4924a7c60d60484"

      def install
        bin.install "cargo-fc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.40/cargo-fc_0.0.40_darwin_arm64.tar.gz"
      sha256 "a371c76dc33adde2d4f95d72518200390524b4ab707588c8470f845d6a88a232"

      def install
        bin.install "cargo-fc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.40/cargo-fc_0.0.40_linux_amd64.tar.gz"
      sha256 "4e428df35f3ae9923d40eea848df2d1bd0528c8ada0850e651700ed0da40d87e"
      def install
        bin.install "cargo-fc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/romnn/cargo-feature-combinations/releases/download/v0.0.40/cargo-fc_0.0.40_linux_arm64.tar.gz"
      sha256 "a7301219cc34899d99c7538368a385463c167e2a0c672949035fe3993f7336a3"
      def install
        bin.install "cargo-fc"
      end
    end
  end
end
