# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confirm < Formula
  desc "A dead simple CLI app that asks the user for a yes/no confirmation"
  homepage ""
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/confirm/releases/download/v1.0.4/confirm_1.0.4_darwin_amd64.tar.gz"
      sha256 "e8484a80a5e141a391ddc4fccb88c79d9ddbdb08a2b448ee991bf0af3c6e3cdd"

      def install
        bin.install "./bin/confirm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/confirm/releases/download/v1.0.4/confirm_1.0.4_darwin_arm64.tar.gz"
      sha256 "c37c1084398330d8cce3e6f065f1d6bc8bf63409231a6308d30254592940ac6a"

      def install
        bin.install "./bin/confirm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/confirm/releases/download/v1.0.4/confirm_1.0.4_linux_amd64.tar.gz"
        sha256 "6254538242e833707442d159ec8e680c3ec948266d8cfa179e0fd780b375df58"

        def install
          bin.install "./bin/confirm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/confirm/releases/download/v1.0.4/confirm_1.0.4_linux_arm64.tar.gz"
        sha256 "5e0f59cdb8b56f713c9e4c3c3ae9df826539937a1a83bc1f8c1d6dabccae333f"

        def install
          bin.install "./bin/confirm"
        end
      end
    end
  end
end
