# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsonschema < Formula
  desc "tiny JSON schema validator"
  homepage ""
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/romnn/gojsonschema-cli/releases/download/v1.0.4/gojsonschema-cli_1.0.4_darwin_amd64.tar.gz"
      sha256 "5e92ba39e5ab7aaced6189ffbd0b80463b5323dadec4c1803648f9cbc8d6d0e9"

      def install
        bin.install "./bin/jsonschema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/romnn/gojsonschema-cli/releases/download/v1.0.4/gojsonschema-cli_1.0.4_darwin_arm64.tar.gz"
      sha256 "f12206db3787067fbf8e4d699a51a4910d7c5f551b6e99c61fbe5d26bb412e0e"

      def install
        bin.install "./bin/jsonschema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/gojsonschema-cli/releases/download/v1.0.4/gojsonschema-cli_1.0.4_linux_amd64.tar.gz"
        sha256 "218f28a37214eadf81daf54977232fbae114f5429068601a07ba51a2d1eedbd6"

        def install
          bin.install "./bin/jsonschema"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/romnn/gojsonschema-cli/releases/download/v1.0.4/gojsonschema-cli_1.0.4_linux_arm64.tar.gz"
        sha256 "acfb6bba10c721a0e1c2dff2e9a76ddf4a00d5c46ec897e17392d8a19296b499"

        def install
          bin.install "./bin/jsonschema"
        end
      end
    end
  end
end
